add uninstall script, improve install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,6 +7,15 @@ echo "| copyright belongs to Allah |"
 echo "------------------------------"
 
 echo ""
+echo "checking dependency.."
+CURL=$(which curl)
+if [[ $CURL == "" ]]; then
+echo ""
+echo "cannot find curl, please insall curl.."
+exit 1
+fi
+
+echo ""
 echo "installing otoressl.."
 echo ""
 
@@ -16,10 +25,20 @@ if [[ ! -d /etc/otoressl ]]; then
 fi
 
 ## Download config
-curl -o /etc/otoressl/config https://raw.githubusercontent.com/deadlyug/otoressl/v1.1/config
+if ! curl -o /etc/otoressl/config https://raw.githubusercontent.com/deadlyug/otoressl/v1.1.1/config; then
+echo ""
+echo "otoressl installation failed.."
+echo "please retry.."
+exit 1
+fi
 
 ## Download script otoressl
-curl -o /bin/otoressl https://raw.githubusercontent.com/deadlyug/otoressl/v1.1/otoressl
+if ! curl -o /bin/otoressl https://raw.githubusercontent.com/deadlyug/otoressl/v1.1.1/otoressl; then
+echo ""
+echo "otoressl installation failed.."
+echo "please retry.."
+exit 1
+fi
 chmod +x /bin/otoressl
 
 echo ""
