change start to enable service crontab to make sure the service hes been enable and started

diff --git a/otoressl b/otoressl
--- a/otoressl
+++ b/otoressl
@@ -159,44 +159,101 @@ if [[ $isCrontab == "" ]]; then
   
   case $OS in
     "Arch")
-      sudo pacman -Syyy cronie
-      systemctl enable --now cronie
+      if sudo pacman -Syyy cronie; then
+        if ! systemctl enable --now cronie; then
+          echo "---------------------------------"
+          echo "cronjob service failed to start.."
+          echo "exiting.."
+        if [[ $1 == "--disable-firewall" ]]; then
+          startFirewall
+        fi
+          exit 1
+        fi
+      else
+        echo "--------------------------------------------------------------------------------------------"
+        echo "Cannot install cronjob package, please install manual cronjob package and rerun this scripts"
+        echo "exiting.."
+      if [[ $1 == "--disable-firewall" ]]; then
+        startFirewall
+      fi
+        exit 1
+      fi
       ;;
     "Ubuntu")
-      apt-get update && apt-get install cron
-      systemctl enable --now cron
+      if apt-get update && apt-get install cron; then
+        if ! systemctl enable --now cron; then
+          echo "---------------------------------"
+          echo "cronjob service failed to start.."
+          echo "exiting.."
+        if [[ $1 == "--disable-firewall" ]]; then
+          startFirewall
+        fi
+          exit 1
+        fi
+      else
+        echo "--------------------------------------------------------------------------------------------"
+        echo "Cannot install cronjob package, please install manual cronjob package and rerun this scripts"
+        echo "exiting.."
+      if [[ $1 == "--disable-firewall" ]]; then
+        startFirewall
+      fi
+        exit 1
+      fi
       ;;
     "CentOS")
-      yum update && yum install crond
-      systemctl enable --now crond
+      if yum update && yum install crond; then
+        if ! systemctl enable --now crond; then
+          echo "---------------------------------"
+          echo "cronjob service failed to start.."
+          echo "exiting.."
+        if [[ $1 == "--disable-firewall" ]]; then
+          startFirewall
+        fi
+          exit 1
+        fi
+      else
+        echo "--------------------------------------------------------------------------------------------"
+        echo "Cannot install cronjob package, please install manual cronjob package and rerun this scripts"
+        echo "exiting.."
+      if [[ $1 == "--disable-firewall" ]]; then
+        startFirewall
+      fi
+        exit 1
+      fi
       ;;
   esac
 else
   case $OS in
     "Arch")
-      if ! systemctl start cronie; then
+      if ! systemctl enable --now cronie; then
         echo "---------------------------------"
         echo "cronjob service failed to start.."
         echo "exiting.."
+      if [[ $1 == "--disable-firewall" ]]; then
         startFirewall
+      fi
         exit 1
       fi
       ;;
     "Ubuntu")
-      if ! systemctl start cron; then
+      if ! systemctl enable --now cron; then
         echo "---------------------------------"
         echo "cronjob service failed to start.."
         echo "exiting.."
+      if [[ $1 == "--disable-firewall" ]]; then
         startFirewall
+      fi
         exit 1
       fi
       ;;
     "CentOS")
-      if ! systemctl start crond; then
+      if ! systemctl enable --now crond; then
         echo "---------------------------------"
         echo "cronjob service failed to start.."
         echo "exiting.."
+      if [[ $1 == "--disable-firewall" ]]; then
         startFirewall
+      fi
         exit 1
       fi
       ;;
@@ -236,4 +293,6 @@ fi
 echo "------------------------------------------------------------"
 echo "berhasil membuat cronjob untuk otomisasi renew certificate.."
 crontab -l
-startFirewall
+if [[ $1 == "--disable-firewall" ]]; then
+  startFirewall
+fi
