add feature trigger a script after renew succeed

diff --git a/otoressl b/otoressl
--- a/otoressl
+++ b/otoressl
@@ -22,7 +22,7 @@ while (( "$#" )); do
       fi
       ;;
     -v|--version)
-      echo "otoressl version 1.2.12"
+      echo "otoressl version 1.3-beta"
       exit 0
       ;;
     -a|--ors-all)
@@ -32,6 +32,15 @@ while (( "$#" )); do
     -s|--ors-single)
       if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
         DOMAIN_NAME=$2
+        shift 2
+      else
+        echo "Error: Argument for $1 is missing" >&2
+        exit 1
+      fi
+      ;;
+    -t|--trigger-script)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        SCRIPT_PATH=$2
         shift 2
       else
         echo "Error: Argument for $1 is missing" >&2
@@ -59,6 +68,8 @@ while (( "$#" )); do
          echo "       iptables - if server use iptables"
          echo "       firewalld - if server use firewalld"
          echo "   -s | --ors-single - single renew"
+         echo "   -t | --trigger-script - trigger a script after successfull renew, you mush supply absolute script path"
+         echo "                           example: --trigger-script /path/to/script"
          echo "   -v - show otoressl version"
          echo "   -w | --restart-webmin - restart webmin after renew"
          echo "   -y - skip confirmation"
@@ -87,6 +98,8 @@ while (( "$#" )); do
          echo "       iptables - if server use iptables"
          echo "       firewalld - if server use firewalld"
          echo "   -s | --ors-single - single renew"
+         echo "   -t | --trigger-script - trigger a script after successfull renew, you mush supply absolute script path"
+         echo "                           example: --trigger-script /path/to/script"
          echo "   -v - show otoressl version"
          echo "   -w | --restart-webmin - restart webmin after renew"
          echo "   -y - skip confirmation"
@@ -138,6 +151,8 @@ if [[ $WEB_SERVER != "nginx" ]]; then
     echo "       iptables - if server use iptables"
     echo "       firewalld - if server use firewalld"
     echo "   -s | --ors-single - single renew"
+    echo "   -t | --trigger-script - trigger a script after successfull renew, you mush supply absolute script path"
+    echo "                           example: --trigger-script /path/to/script"
     echo "   -v - show otoressl version"
     echo "   -w | --restart-webmin - restart webmin after renew"
     echo "   -y - skip confirmation"
@@ -419,6 +434,23 @@ function getValidDay() {
 }
 
 # RENEW-SECTION
+if [[ $SCRIPT_PATH != "" ]]; then
+  getFirstCharacter=$(echo ${SCRIPT_PATH:0:1})
+  if [[ $getFirstCharacter != "/" ]]; then
+    echo "------"
+    echo "Error!"
+    echo "$SCRIPT_PATH script is not absolute path.."
+    exit 1
+  else
+    if [[ ! -f $SCRIPT_PATH ]]; then
+      echo "------"
+      echo "Error!"
+      echo "Cannot find $SCRIPT_PATH script.."
+      exit 1
+    fi
+  fi
+fi
+
 getValidDay;
 
 if [[ $certbot == "" ]]; then
@@ -514,6 +546,12 @@ Renewing certificate..
           esac
         ;;
     esac
+
+    if [[ $SCRIPT_PATH != "" ]]; then
+      if [[ -f $SCRIPT_PATH ]]; then
+        bash $SCRIPT_PATH;
+      fi
+    fi
     
     if [[ $RESTART_WEBMIN ]]; then
       initSystem restart webmin
@@ -673,51 +711,74 @@ month=$(date --date="+$renewDay days" +%-m)
 day=$(date --date="+$renewDay days" +%-d)
 
 function cronjob() {
+  function cronFirewall() {
+    if [[ $RESTART_WEBMIN ]]; then
+        if [[ $DOMAIN_NAME != "" ]]; then
+            if [[ $SCRIPT_PATH != "" ]]; then
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --restart-webmin --ors-single $DOMAIN_NAME" --trigger-script $SCRIPT_PATH; } | crontab -
+              else
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --restart-webmin --ors-single $DOMAIN_NAME"; } | crontab -
+            fi
+         else
+            if [[ $SCRIPT_PATH != "" ]]; then
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --restart-webmin --ors-all" --trigger-script $SCRIPT_PATH; } | crontab -
+              else
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --restart-webmin --ors-all"; } | crontab -
+            fi
+        fi
+    else
+      if [[ $DOMAIN_NAME != "" ]]; then
+        if [[ $SCRIPT_PATH != "" ]]; then
+          { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --ors-single $DOMAIN_NAME"; } | crontab -
+        else
+          { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --ors-single $DOMAIN_NAME"; } | crontab -
+        fi
+      else
+        if [[ $SCRIPT_PATH != "" ]]; then
+          { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --ors-all --trigger-script $SCRIPT_PATH"; } | crontab -
+        else
+          { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --disable-firewall $1 --ors-all"; } | crontab -
+        fi
+      fi
+    fi
+  }
   if [[ $FIREWALL != "" ]]; then
     case $FIREWALL in
       "iptables")
-        if [[ $RESTART_WEBMIN ]]; then
-            if [[ $DOMAIN_NAME != "" ]]; then
-                { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall iptables --restart-webmin --ors-single $DOMAIN_NAME"; } | crontab -
-              else
-                { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall iptables --restart-webmin --ors-all"; } | crontab -
-            fi
-          else
-            if [[ $DOMAIN_NAME != "" ]]; then
-              { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall iptables --ors-single $DOMAIN_NAME"; } | crontab -
-            else
-              { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall iptables --ors-all"; } | crontab -
-            fi
-        fi
+        cronFirewall "iptables";
         ;;
       "firewalld")
-        if [[ $RESTART_WEBMIN ]]; then
-            if [[ $DOMAIN_NAME != "" ]]; then
-                { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall firewalld --restart-webmin --ors-single $DOMAIN_NAME"; } | crontab -
-              else
-                { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall firewalld --restart-webmin --ors-all"; } | crontab -
-            fi
-          else
-            if [[ $DOMAIN_NAME != "" ]]; then
-              { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall firewalld --ors-single $DOMAIN_NAME"; } | crontab -
-            else
-              { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --disable-firewall firewalld --ors-all"; } | crontab -
-            fi
-        fi
+        cronFirewall "firewalld";
         ;;
     esac
   else
     if [[ $RESTART_WEBMIN ]]; then
       if [[ $DOMAIN_NAME != "" ]]; then
-        { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --restart-webmin --ors-single $DOMAIN_NAME"; } | crontab -
+          if [[ $SCRIPT_PATH != "" ]]; then
+            { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --restart-webmin --ors-single $DOMAIN_NAME" --trigger-script $SCRIPT_PATH; } | crontab -
+            else
+            { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --restart-webmin --ors-single $DOMAIN_NAME"; } | crontab -
+          fi
         else
-        { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --restart-webmin --ors-all"; } | crontab -
+          if [[ $SCRIPT_PATH != "" ]]; then
+            { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --restart-webmin --ors-all --trigger-script $SCRIPT_PATH"; } | crontab -
+            else
+            { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --restart-webmin --ors-all"; } | crontab -
+          fi
       fi
       else
         if [[ $DOMAIN_NAME != "" ]]; then
-          { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --ors-single $DOMAIN_NAME"; } | crontab -
+            if [[ $SCRIPT_PATH != "" ]]; then
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --ors-single $DOMAIN_NAME --trigger-script $SCRIPT_PATH"; } | crontab -
+            else
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --ors-single $DOMAIN_NAME"; } | crontab -
+            fi
           else
-          { crontab -l; echo "0 9 $day $month * $(which otoressl) $1 -y --ors-all"; } | crontab -
+            if [[ $SCRIPT_PATH != "" ]]; then
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --ors-all --trigger-script $SCRIPT_PATH"; } | crontab -
+            else
+              { crontab -l; echo "0 9 $day $month * $(which otoressl) $SERVER_PROVIDER -y --ors-all"; } | crontab -
+            fi
         fi
     fi
   fi
@@ -725,10 +786,12 @@ function cronjob() {
 
 case $WEB_SERVER in
   "nginx")
-      cronjob nginx;
+      SERVER_PROVIDER="nginx"
+      cronjob;
     ;;
   "apache")
-      cronjob apache;
+      SERVER_PROVIDER="apache"
+      cronjob;
     ;;
 esac
 
