make auto restart web server

diff --git a/otoressl b/otoressl
--- a/otoressl
+++ b/otoressl
@@ -2,6 +2,14 @@
 # Change directory to directory of the script
 cd "$(dirname "$0")"
 
+if [[ ! $1 == "nginx" ]] || [[ ! $1 == "httpd" ]]; then
+  echo "-----"
+  echo "Error"
+  echo "you must specify web server service to tell script to auto restart web server that you have been chosen.."
+  echo "example: ./otoressl nginx or ./otoressl httpd"
+  exit 1
+fi
+
 OS=$(hostnamectl | grep "Operating System" | awk '{print $3}')
 certbot=$(which certbot)
 if [[ $certbot == "" ]]; then
@@ -13,8 +21,8 @@ if [[ $certbot == "" ]]; then
 fi
 validDay=$(certbot certificates | grep Expiry | awk 'FNR==1 {print $6}')
 
-option1=$1
-firewall=$2
+option1=$2
+firewall=$3
 function startFirewall() {
 
 case $OS in
@@ -67,8 +75,8 @@ esac
 
 case $OS in
   "CentOS")
-    if [[ $1 == "--disable-firewall" ]]; then
-      case $2 in
+    if [[ $2 == "--disable-firewall" ]]; then
+      case $3 in
         "iptables")
           echo "--------------------------"
           echo "menon-aktifkan firewall.."
@@ -87,8 +95,8 @@ case $OS in
     fi
     ;;
   *)
-    if [[ $1 == "--disable-firewall" ]]; then
-      case $2 in
+    if [[ $2 == "--disable-firewall" ]]; then
+      case $3 in
         "iptables")
           if [[ ! -d /etc/sysconfig ]]; then
             mkdir /etc/sysconfig
@@ -168,7 +176,7 @@ if [[ $isCrontab == "" ]]; then
           echo "---------------------------------"
           echo "cronjob service failed to start.."
           echo "exiting.."
-        if [[ $1 == "--disable-firewall" ]]; then
+        if [[ $2 == "--disable-firewall" ]]; then
           startFirewall
         fi
           exit 1
@@ -177,7 +185,7 @@ if [[ $isCrontab == "" ]]; then
         echo "--------------------------------------------------------------------------------------------"
         echo "Cannot install cronjob package, please install manual cronjob package and rerun this scripts"
         echo "exiting.."
-      if [[ $1 == "--disable-firewall" ]]; then
+      if [[ $2 == "--disable-firewall" ]]; then
         startFirewall
       fi
         exit 1
@@ -189,7 +197,7 @@ if [[ $isCrontab == "" ]]; then
           echo "---------------------------------"
           echo "cronjob service failed to start.."
           echo "exiting.."
-        if [[ $1 == "--disable-firewall" ]]; then
+        if [[ $2 == "--disable-firewall" ]]; then
           startFirewall
         fi
           exit 1
@@ -198,7 +206,7 @@ if [[ $isCrontab == "" ]]; then
         echo "--------------------------------------------------------------------------------------------"
         echo "Cannot install cronjob package, please install manual cronjob package and rerun this scripts"
         echo "exiting.."
-      if [[ $1 == "--disable-firewall" ]]; then
+      if [[ $2 == "--disable-firewall" ]]; then
         startFirewall
       fi
         exit 1
@@ -210,7 +218,7 @@ if [[ $isCrontab == "" ]]; then
           echo "---------------------------------"
           echo "cronjob service failed to start.."
           echo "exiting.."
-        if [[ $1 == "--disable-firewall" ]]; then
+        if [[ $2 == "--disable-firewall" ]]; then
           startFirewall
         fi
           exit 1
@@ -219,7 +227,7 @@ if [[ $isCrontab == "" ]]; then
         echo "--------------------------------------------------------------------------------------------"
         echo "Cannot install cronjob package, please install manual cronjob package and rerun this scripts"
         echo "exiting.."
-      if [[ $1 == "--disable-firewall" ]]; then
+      if [[ $2 == "--disable-firewall" ]]; then
         startFirewall
       fi
         exit 1
@@ -233,7 +241,7 @@ else
         echo "---------------------------------"
         echo "cronjob service failed to start.."
         echo "exiting.."
-      if [[ $1 == "--disable-firewall" ]]; then
+      if [[ $2 == "--disable-firewall" ]]; then
         startFirewall
       fi
         exit 1
@@ -244,7 +252,7 @@ else
         echo "---------------------------------"
         echo "cronjob service failed to start.."
         echo "exiting.."
-      if [[ $1 == "--disable-firewall" ]]; then
+      if [[ $2 == "--disable-firewall" ]]; then
         startFirewall
       fi
         exit 1
@@ -255,7 +263,7 @@ else
         echo "---------------------------------"
         echo "cronjob service failed to start.."
         echo "exiting.."
-      if [[ $1 == "--disable-firewall" ]]; then
+      if [[ $2 == "--disable-firewall" ]]; then
         startFirewall
       fi
         exit 1
@@ -272,18 +280,36 @@ renewDay="$(($validDay - 10))"
 month=$(date --date="+$renewDay days" +%-m)
 day=$(date --date="+$renewDay days" +%-d)
 
-if [[ $1 == "--disable-firewall" ]]; then
-  case $2 in
-    "iptables")
-      { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl --disable-firewall iptables"; } | crontab -
-      ;;
-    "firewalld")
-      { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl --disable-firewall firewalld"; } | crontab -
-      ;;
-  esac
-else
-  { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl"; } | crontab -
-fi
+case $1 in
+  "nginx")
+      if [[ $2 == "--disable-firewall" ]]; then
+        case $3 in
+          "iptables")
+            { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl nginx --disable-firewall iptables"; } | crontab -
+            ;;
+          "firewalld")
+            { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl nginx --disable-firewall firewalld"; } | crontab -
+            ;;
+        esac
+      else
+        { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl nginx"; } | crontab -
+      fi
+    ;;
+  "httpd")
+      if [[ $2 == "--disable-firewall" ]]; then
+        case $3 in
+          "iptables")
+            { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl httpd --disable-firewall iptables"; } | crontab -
+            ;;
+          "firewalld")
+            { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl httpd --disable-firewall firewalld"; } | crontab -
+            ;;
+        esac
+      else
+        { crontab -l; echo "0 9 $day $month * $(which bash) $(pwd)/otoressl httpd"; } | crontab -
+      fi
+    ;;
+esac
 
 if [[ -f ./send-notify ]]; then
    ./send-notify "berhasil membuat cronjob untuk otomisasi renew certificate.."
@@ -297,6 +323,109 @@ fi
 echo "------------------------------------------------------------"
 echo "berhasil membuat cronjob untuk otomisasi renew certificate.."
 crontab -l
-if [[ $1 == "--disable-firewall" ]]; then
+if [[ $2 == "--disable-firewall" ]]; then
   startFirewall
 fi
+
+case $OS in
+  "Ubuntu")
+      case $1 in
+        "nginx")
+          if ! systemctl restart nginx; then
+            echo "----"
+            echo "Failed to restart nginx.."
+            echo "Maybe httpd is running and use the same port with nginx"
+            echo "Try to stop httpd.."
+            if systemctl status httpd; then
+              if systemctl stop httpd; then
+                if ! systemctl restart nginx; then
+                  "httpd has been stop but still cannot start, maybe something were wrong with nginx configuration.. "
+                  if systemctl start httpd; then
+                    "Success restart httpd.."
+                  fi
+                  exit 1
+                fi
+              fi
+             else
+            "cannot stop httpd, maybe the service already stop. it makes maybe there's a error with you nginx configuration.."
+            fi
+          else
+            echo "Success restart nginx.."
+          fi
+          ;;
+        "httpd")
+          if ! systemctl restart apache2; then
+            echo "----"
+            echo "Failed to restart httpd.."
+            echo "Maybe httpd is running and use the same port with nginx"
+            echo "Try to stop httpd.."
+            if systemctl status nginx; then
+              if systemctl stop nginx; then
+                if ! systemctl restart apache2; then
+                  "httpd has been stop but still cannot start, maybe something were wrong with nginx configuration.. "
+                  if systemctl start nginx; then
+                    "Success restart nginx.."
+                  fi
+                  exit 1
+                fi
+              fi
+             else
+            "cannot stop nginx, maybe the service already stop. it makes maybe there's a error with you httpd configuration.."
+            fi
+          else
+            echo "Success restart httpd.."
+          fi
+          ;;
+      esac
+    ;;
+  *)
+      case $1 in
+        "nginx")
+          if ! systemctl restart nginx; then
+            echo "-------------------------"
+            echo "Failed to restart nginx.."
+            echo "Maybe httpd is running and use the same port with nginx"
+            echo "Try to stop httpd.."
+            if systemctl status httpd; then
+              if systemctl stop httpd; then
+                if ! systemctl restart nginx; then
+                  "httpd has been stop but still cannot start, maybe something were wrong with nginx configuration.. "
+                  if systemctl start httpd; then
+                    "Success restart httpd.."
+                  fi
+                  exit 1
+                fi
+              fi
+             else
+            "cannot stop httpd, maybe the service already stop. it makes maybe there's a error with you nginx configuration.."
+            fi
+          else
+            echo "Success restart nginx.."
+          fi
+          ;;
+        "httpd")
+          if ! systemctl restart httpd; then
+            echo "-------------------------"
+            echo "Failed to restart httpd.."
+            echo "Maybe httpd is running and use the same port with nginx"
+            echo "Try to stop httpd.."
+            if systemctl status nginx; then
+              if systemctl stop nginx; then
+                if ! systemctl restart httpd; then
+                  "httpd has been stop but still cannot start, maybe something were wrong with nginx configuration.. "
+                  if systemctl start nginx; then
+                    "Success restart nginx.."
+                  fi
+                  exit 1
+                fi
+              fi
+             else
+            "cannot stop nginx, maybe the service already stop. it makes maybe there's a error with you httpd configuration.."
+            fi
+          else
+            echo "Success restart httpd.."
+          fi
+          ;;
+      esac
+    ;;
+esac
